export interface Country {
  code: string;
  name: string;
  flag: string;
}

export const COUNTRIES: Country[] = [
  { code: "al", name: "Albania", flag: "🇦🇱" },
  { code: "ar", name: "Argentina", flag: "🇦🇷" },
  { code: "au", name: "Australia", flag: "🇦🇺" },
  { code: "at", name: "Austria", flag: "🇦🇹" },
  { code: "be", name: "Belgium", flag: "🇧🇪" },
  { code: "ba", name: "Bosnia and Herzegovina", flag: "🇧🇦" },
  { code: "br", name: "Brazil", flag: "🇧🇷" },
  { code: "bg", name: "Bulgaria", flag: "🇧🇬" },
  { code: "ca", name: "Canada", flag: "🇨🇦" },
  { code: "cl", name: "Chile", flag: "🇨🇱" },
  { code: "co", name: "Colombia", flag: "🇨🇴" },
  { code: "hr", name: "Croatia", flag: "🇭🇷" },
  { code: "cy", name: "Cyprus", flag: "🇨🇾" },
  { code: "cz", name: "Czech Republic", flag: "🇨🇿" },
  { code: "dk", name: "Denmark", flag: "🇩🇰" },
  { code: "ee", name: "Estonia", flag: "🇪🇪" },
  { code: "fi", name: "Finland", flag: "🇫🇮" },
  { code: "fr", name: "France", flag: "🇫🇷" },
  { code: "ge", name: "Georgia", flag: "🇬🇪" },
  { code: "de", name: "Germany", flag: "🇩🇪" },
  { code: "gr", name: "Greece", flag: "🇬🇷" },
  { code: "hk", name: "Hong Kong", flag: "🇭🇰" },
  { code: "hu", name: "Hungary", flag: "🇭🇺" },
  { code: "is", name: "Iceland", flag: "🇮🇸" },
  { code: "in", name: "India", flag: "🇮🇳" },
  { code: "id", name: "Indonesia", flag: "🇮🇩" },
  { code: "ie", name: "Ireland", flag: "🇮🇪" },
  { code: "il", name: "Israel", flag: "🇮🇱" },
  { code: "it", name: "Italy", flag: "🇮🇹" },
  { code: "jp", name: "Japan", flag: "🇯🇵" },
  { code: "lv", name: "Latvia", flag: "🇱🇻" },
  { code: "lt", name: "Lithuania", flag: "🇱🇹" },
  { code: "lu", name: "Luxembourg", flag: "🇱🇺" },
  { code: "mk", name: "North Macedonia", flag: "🇲🇰" },
  { code: "my", name: "Malaysia", flag: "🇲🇾" },
  { code: "mx", name: "Mexico", flag: "🇲🇽" },
  { code: "md", name: "Moldova", flag: "🇲🇩" },
  { code: "nl", name: "Netherlands", flag: "🇳🇱" },
  { code: "nz", name: "New Zealand", flag: "🇳🇿" },
  { code: "ng", name: "Nigeria", flag: "🇳🇬" },
  { code: "no", name: "Norway", flag: "🇳🇴" },
  { code: "pl", name: "Poland", flag: "🇵🇱" },
  { code: "pt", name: "Portugal", flag: "🇵🇹" },
  { code: "ro", name: "Romania", flag: "🇷🇴" },
  { code: "rs", name: "Serbia", flag: "🇷🇸" },
  { code: "sg", name: "Singapore", flag: "🇸🇬" },
  { code: "sk", name: "Slovakia", flag: "🇸🇰" },
  { code: "si", name: "Slovenia", flag: "🇸🇮" },
  { code: "za", name: "South Africa", flag: "🇿🇦" },
  { code: "kr", name: "South Korea", flag: "🇰🇷" },
  { code: "es", name: "Spain", flag: "🇪🇸" },
  { code: "se", name: "Sweden", flag: "🇸🇪" },
  { code: "ch", name: "Switzerland", flag: "🇨🇭" },
  { code: "tw", name: "Taiwan", flag: "🇹🇼" },
  { code: "th", name: "Thailand", flag: "🇹🇭" },
  { code: "tr", name: "Turkey", flag: "🇹🇷" },
  { code: "ua", name: "Ukraine", flag: "🇺🇦" },
  { code: "gb", name: "United Kingdom", flag: "🇬🇧" },
  { code: "us", name: "United States", flag: "🇺🇸" },
  { code: "vn", name: "Vietnam", flag: "🇻🇳" },
];

export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find(c => c.code === code.toLowerCase());
}
